

version: "3.9"
services:
  web:
    image: 039978326156.dkr.ecr.us-east-2.amazonaws.com/degmi/frontend:latest
    container_name: web
    build: ../frontend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_HOST=backend
      - BACKEND_API_PORT=8080
      - NODE_ENV=prod

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dedb
      - APP_DB_NAME=degmi
      - APP_DB_USER=degmi 
      - APP_DB_PASS=degmi
    ports:
      - "5432:5432"

  backend:
    image: 039978326156.dkr.ecr.us-east-2.amazonaws.com/degmi/backend:latest
    container_name: backend
    volumes:
    - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh
    - ./start-backend.sh:/usr/src/app/start-backend.sh
    build: ../backend
    environment:
     - DEV_DB_HOST=db
    ports:
     - "8080:8080"
    depends_on:
     - "db"

    command: ["bash", "./wait-for-it.sh", "db:5432", "--timeout=0", "--strict", "--", "bash", "./start-backend.sh"]

  