apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
  namespace: gmi
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - command: ["bash", "./wait-for-it.sh", "db:5432", "--timeout=0", "--strict", "--", "bash", "./start-backend.sh"]
          env:
             - name: NODE_ENV
               value: "production"
             - name: ONET_NAME
               value: "expona"
             - name: ONET_PSWD
               value: "4696tug"
             - name: DB_USER
               value: "postgresExpona"
             - name: DB_PASS
               value: "ExponaPassword1234"
             - name: DB_NAME
               value: "dedb"
             - name: DB_HOST
               value: "db"
             - name: DB_PORT
               value: "5432"
             - name: DEV_DB_HOST
               value: "db"
             - name: POSTGRES_USER
               value: "postgresExpona"
             - name: POSTGRES_DB
               value: "ExponaPassword1234"
             - name: APP_DB_NAME
               value: "dedb"
             - name: APP_DB_USER
               value: "expona"
             - name: APP_DB_PASS
               value: "ExponaPassword1234"
          image: registry.gitlab.com/de4512928/saas/backend:latest
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      imagePullSecrets: 
        - name: registry-credentials
      restartPolicy: Always
status: {}
