apiVersion: v1
kind: ConfigMap
metadata:
  name: dedb-initdb-config
  namespace: gmi
data:
  initdb.sql: |
    DROP DATABASE $APP_DB_NAME;
    CREATE USER $APP_DB_USER WITH SUPERUSER PASSWORD '$APP_DB_PASS';
    CREATE DATABASE $APP_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
    ALTER USER $APP_DB_USER with SUPERUSER;

