apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: api.digitalexhaust.ai
      http:
        paths:
          - path: /(.*)
            backend:
              service:
                name: backend
                port:
                  number: 8080
            pathType: Prefix
    - host: app.digitalexhaust.ai
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000                  